[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://www.lumeth.com/*"
  to = "https://lumeth.com/:splat"
  status = 301

[[redirects]]
  from = "http://lumeth.com/*"
  to = "https://lumeth.com/:splat"
  status = 301

[[redirects]]
  from = "http://www.lumeth.com/*"
  to = "https://lumeth.com/:splat"
  status = 301

[[redirects]]
  from = "/app/*"
  to = "/get-started"
  status = 301

[[redirects]]
  from = "/download"
  to = "/get-started"
  status = 301

[[redirects]]
  from = "/salon/*"
  to = "/business"
  status = 301

[[redirects]]
  from = "/professional/*"
  to = "/business"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "https://api.lumeth.com/:splat"
  status = 200
